"""Initial schema

Revision ID: 33cdd27dae19
Revises: 
Create Date: 2026-05-02 22:13:03.243359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cdd27dae19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.BigInteger(), nullable=False, comment='The Discord Message ID of the game embed'),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='The Discord Snowflake ID of the server where the game was played'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the game result was committed to the database'),
    sa.Column('voting_timer', sa.Integer(), nullable=False, comment='The specific voting duration (in seconds) used for this game session'),
    sa.Column('winning_channel_id', sa.BigInteger(), nullable=True, comment='The ID of the voice channel/team that won the game'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_guild_id'), 'games', ['guild_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Internal primary key for the subscription record'),
    sa.Column('target_id', sa.BigInteger(), nullable=False, comment='The Discord User ID or Guild ID that owns this subscription'),
    sa.Column('type', sa.Enum('USER', 'GUILD', name='subscriptiontype'), nullable=False, comment='Defines if the subscription applies to a single user or an entire server'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Quick-check flag to see if the subscription is currently valid'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='The exact timestamp when premium access should be revoked'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_target_id'), 'subscriptions', ['target_id'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='The unique Discord Snowflake ID for the user'),
    sa.Column('username', sa.String(length=32), nullable=False, comment='The Discord username of the player at the time of last record'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('game_players',
    sa.Column('game_id', sa.BigInteger(), nullable=False, comment='Reference to the game session'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Reference to the user'),
    sa.Column('channel_id', sa.BigInteger(), nullable=False, comment='The ID of the voice channel this player was assigned to'),
    sa.Column('is_thrower', sa.Boolean(), nullable=False, comment='Whether the player was secretly assigned to lose the game'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    op.create_index(op.f('ix_game_players_channel_id'), 'game_players', ['channel_id'], unique=False)
    op.create_table('votes',
    sa.Column('game_id', sa.BigInteger(), nullable=False, comment='Reference to the game session where the vote occurred'),
    sa.Column('voter_id', sa.BigInteger(), nullable=False, comment='The ID of the player who cast the vote'),
    sa.Column('target_id', sa.BigInteger(), nullable=False, comment='The ID of the player being accused'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'voter_id', 'target_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_index(op.f('ix_game_players_channel_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_target_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_games_guild_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
