"""add_elo_stat_columns_guild_settings_user_id_index

Revision ID: 6b92ded8e60a
Revises: a07cb89bc77a
Create Date: 2026-06-20 18:19:07.890532

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b92ded8e60a"
down_revision: Union[str, Sequence[str], None] = "a07cb89bc77a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_settings",
        sa.Column("guild_id", sa.BigInteger(), nullable=False, comment="The Discord Snowflake ID of the server"),
        sa.Column(
            "voting_timer",
            sa.Integer(),
            server_default="60",
            nullable=False,
            comment="Voting phase duration in seconds",
        ),
        sa.Column(
            "thrower_info",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether throwers are told about teammates who are also throwers",
        ),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    op.create_index(op.f("ix_game_players_user_id"), "game_players", ["user_id"], unique=False)
    op.add_column(
        "users",
        sa.Column("games_played", sa.Integer(), server_default="0", nullable=False, comment="Total matches completed"),
    )
    op.add_column(
        "users",
        sa.Column(
            "games_won",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Total matches won regardless of role",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "games_as_thrower",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="How many times this user was assigned the Secret Thrower role",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "games_thrown",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Games where user was the Thrower and their team lost (successful bluff)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_votes_received",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Total votes cast against this user by others",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "votes_received_as_thrower",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Votes received while user was actually the thrower (Caught count)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_votes_cast",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Total number of votes this user has sent",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "votes_cast_on_thrower",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="How many times this user correctly voted for the actual thrower",
        ),
    )
    op.add_column("users", sa.Column("innocent_elo", sa.Float(), nullable=False))
    op.add_column("users", sa.Column("thrower_elo", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "thrower_elo")
    op.drop_column("users", "innocent_elo")
    op.drop_column("users", "votes_cast_on_thrower")
    op.drop_column("users", "total_votes_cast")
    op.drop_column("users", "votes_received_as_thrower")
    op.drop_column("users", "total_votes_received")
    op.drop_column("users", "games_thrown")
    op.drop_column("users", "games_as_thrower")
    op.drop_column("users", "games_won")
    op.drop_column("users", "games_played")
    op.drop_index(op.f("ix_game_players_user_id"), table_name="game_players")
    op.drop_table("guild_settings")
    # ### end Alembic commands ###
