"""drop_games_voting_timer

Revision ID: 900a4977190a
Revises: 6b92ded8e60a
Create Date: 2026-06-20 18:33:11.498452

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "900a4977190a"
down_revision: Union[str, Sequence[str], None] = "6b92ded8e60a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "voting_timer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "voting_timer",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="The specific voting duration (in seconds) used for this game session",
        ),
    )
    # ### end Alembic commands ###
